affinity: {}
fullNameOverride: hasura
image:
  pullPolicy: IfNotPresent
  repository: hasura/graphql-engine
ingress:
  annotations: {}
  enabled: true
  hosts:
    - host: hasura.yougotbud.com
      paths:
        - /
  tls:
    - hosts:
        - hasura.yougotbud.com
      secretName: hasura-tls
nameOverride: hasura
nodeSelector: {}
postgresDbUrl: postgres://postgres:example@timescaledb.default.svc.cluster.local:5432/postgres
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 600Mi
service:
  port: 80
  type: LoadBalancer
tolerations: []
