{{- if .Values.adminSecret -}}
{{- $fullName := include "hasura.fullname" . -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ $fullName }}-admin-secret
data: 
  secret: {{ .Values.adminSecret }}
{{- end }}