apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hasura.fullname" . }}
  labels:
{{ include "hasura.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hasura.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hasura.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: HASURA_GRAPHQL_DATABASE_URL
            value: {{ .Values.postgresDbUrl }}
         {{- if .Values.enableConsole -}}
          - name: HASURA_GRAPHQL_ENABLE_CONSOLE
            value: "true"
         {{- end }}
         {{- if .Values.adminSecret -}}
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            value:  "{{ .Values.adminSecret }}"
         {{- end }}
         {{- if .Values.jwtSecret }}
          - name: HASURA_GRAPHQL_JWT_SECRET
            value: "{{ .Files.Get .Values.jwtSecret | toPrettyJson }}"
         {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
