{{- if .Values.jwtSecret -}}
{{- $fullName := include "hasura.fullname" . -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ $fullName }}-jwt-secret
data: 
  secret: {{ .Files.Get .Values.jwtSecret | toPrettyJson | quote }}
{{- end }}